services:
  # ─── User service ─────────────────────────────────────────────────────────
  user:
    build:
      context: .
      dockerfile: services/user_service/Dockerfile
    env_file: .env
    ports:
      - "8001:8001"

  # ─── Project service ──────────────────────────────────────────────────────
  project:
    build:
      context: .
      dockerfile: services/project_service/Dockerfile
    env_file: .env
    environment:
      GATEWAY_URL: "http://realtime-gateway:9000"
      GATEWAY_INTERNAL_SECRET: "${GATEWAY_INTERNAL_SECRET}"
    depends_on:
      - user
      - realtime-gateway
    ports:
      - "8002:8002"

  # ─── Analytics service ───────────────────────────────────────────────────
  analytics:
    build:
      context: .
      dockerfile: services/analytics_service/Dockerfile
    env_file: .env
    environment:
      GATEWAY_URL: "http://realtime-gateway:9000"
      GATEWAY_INTERNAL_SECRET: "${GATEWAY_INTERNAL_SECRET}"
    depends_on:
      - user
      - project
      - realtime-gateway
    ports:
      - "8003:8003"

  # ─── Notification service ─────────────────────────────────────────────────
  notification:
    build:
      context: .
      dockerfile: services/notification_service/Dockerfile
    env_file: .env
    environment:
      GATEWAY_URL: "http://realtime-gateway:9000"
      GATEWAY_INTERNAL_SECRET: "${GATEWAY_INTERNAL_SECRET}"
    depends_on:
      - project
      - realtime-gateway
    ports:
      - "8004:8004"

  # ─── Scheduler service ───────────────────────────────────────────────────
  scheduler:
    build:
      context: .
      dockerfile: services/scheduler_service/Dockerfile
    env_file: .env
    environment:
      GATEWAY_URL: "http://realtime-gateway:9000"
      GATEWAY_INTERNAL_SECRET: "${GATEWAY_INTERNAL_SECRET}"
    depends_on:
      - realtime-gateway
    ports:
      - "8005:8005"

  # ─── Realtime-gateway ─────────────────────────────────────────────────────
  realtime-gateway:
    build:
      context: .
      dockerfile: services/realtime_gateway/Dockerfile
    env_file: .env
    depends_on:
      - user
    ports:
      - "9000:9000"

  # ─── AI service ───────────────────────────────────────────────────────────
  ai:
    build:
      context: .
      dockerfile: services/ai_service/Dockerfile
    env_file: .env
    depends_on:
      - user
    ports:
      - "8006:8006"

  # ─── Nginx frontend proxy ─────────────────────────────────────────────────
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - realtime-gateway
      - project
